playground/App.tsx
playground/LuckyDraw.tsx

[EVENT-3065](https://17media.atlassian.net/jira/software/projects/EVENT/boards/60/backlog?assignee=608fae47000224006a703321&selectedIssue=EVENT-3065)

chore: use lucky draw sample code.

---

lib/components/TransitionLeaderboardWrapper.tsx
lib/hooks/__test__/luckydraw.test.ts
lib/hooks/__test__/setupTests.ts
lib/hooks/useLuckyDraw.tsx
lib/utils.ts
playground/LuckyDraw.tsx

- 增加 clearWinners(), reset() function.
- 增加 allWinners. 
- 使用 localstorage 紀錄 key: url - value: allWinners 提供使用

[EVENT-3081] Feat/use lucky draw add enhance

---

lib/hooks/__test__/luckydraw.test.ts
lib/hooks/useLuckyDraw.tsx
playground/LuckyDraw.tsx

- 增加 `willAutoDrawRemainCount`
- 增加 `currentRound`

feat: add willAutoDrawRemainCount, move currentRound inside hooks

---

.prettier.js
.prettierrc
lib/hooks/__test__/luckydraw.test.ts
lib/hooks/__test__/setupTests.ts
lib/hooks/useLuckyDraw.tsx
playground/App.tsx
playground/LuckyDraw.tsx

增加開獎 animation（可選用 or 不用 by MaskDiv with hasDraw)

feat: add draw animation

---

lib/hooks/useTypeApi.ts

[APP-25720](https://17media.atlassian.net/browse/APP-25720)
修正isloading一開始都是true的問題

fix: fix is loading init true bug

---

lib/17appTrack.ts
lib/hooks/index.ts
lib/hooks/useFilter.ts
lib/utils.ts
package.json
yarn.lock

[APP-26899](https://17media.atlassian.net/browse/APP-26899)
將refactor/web99-2106-tw-anniversary6裡的useFilter移植

feat: userFilter migrate

---

.eslintrc.js
lib/hooks/useFilter.ts
package-lock.json
package.json
yarn.lock

[APP-26899](https://17media.atlassian.net/browse/APP-26899)
重構useFilter

feat: [APP-26899] useFilter refactot

---

lib/hooks/useFilter.ts
playground/App.tsx
playground/Filter.tsx
playground/TypeApi.tsx

[APP-26900](https://17media.atlassian.net/browse/APP-26900)
1. 新建playground，預備假榜單資料，使用useFilter filter資料
2. 在原本TypeApi新增useFilter功能，使用實際api資料做filter功能

feat: [APP-26900] useFilter playground

---

lib/hooks/__test__/filter.test.ts

[APP-26901](https://17media.atlassian.net/browse/APP-26901)
新建 jest test，預備假榜單資料，測試 useFilter filter資料

feat: add jest test for useFilter

---

lib/hooks/useFilter.ts

[APP-26902](https://17media.atlassian.net/browse/APP-26902)
新建 useFilter type doc

feat: add type doc

---

lib/utils.ts
playground/Utils.tsx

- 修改 getCurrentTranslateLang
改成 return enum RegionLanguage
新增
- getStringDateByLocalFormat
- getStringDateCountdownByLocalFormat
- convertDateToTime

[APP-27187] a few i18n functions

---

lib/hooks/useFollower.ts
lib/service/follower.service.ts
playground/App.tsx
playground/Follower.tsx

[APP-27749](https://17media.atlassian.net/browse/APP-27749)

[APP-27749] feat: add useFollower and playground

---

lib/hooks/__test__/startRender.test.ts
lib/hooks/useStartRender.ts
playground/App.tsx
playground/StartRender.tsx

[APP-28302](https://17media.atlassian.net/browse/APP-28302)
[APP-28303](https://17media.atlassian.net/browse/APP-28303)
[APP-28304](https://17media.atlassian.net/browse/APP-28304)
[APP-28305](https://17media.atlassian.net/browse/APP-28305)
完成 useStartRender 移植和playground

Feat/app 25723/use start render

---

lib/hooks/useScore.ts
lib/utils.ts
playground/App.tsx
playground/Follower.tsx
playground/Score.tsx

codebase: [APP-28529](https://17media.atlassian.net/browse/APP-28529)
typedoc: [APP-28530](https://17media.atlassian.net/browse/APP-28530)

[APP-25724] feat: add useScore playground

---

playground/Score.tsx

[APP-28687](https://17media.atlassian.net/browse/APP-28687)
[APP-28703](https://17media.atlassian.net/browse/APP-28703)
都是 input 超過 maximum 時會有怪數字 bug
- 設限 input maximum
- 補描述

 [APP-28687][APP-28703] fix: number maximum bug

---

lib/hooks/useTypeApi.ts
lib/service/leaderboardEventory.service.ts
playground/App.tsx
playground/TypeApi.tsx
playground/TypeApi2.tsx

[APP-27833](https://17media.atlassian.net/browse/APP-27833)
在取得第一次backend response時就開始render畫面，再次取得下一次response再加上新的render畫面

feat: [APP-27833] enhance useTypeApi

---

lib/17liveMessageTunnel.tsx
lib/helpers/handleClickAvatar.ts
lib/types.ts
lib/utils.ts
playground/TypeApi.tsx
playground/TypeApi2.tsx

[APP-28969](https://17media.atlassian.net/browse/APP-28969)
- rename to helpers/handleClickAvatar
- 其行為不方便用 playground 呈現, 加在 useTypeApi, useTypeApi2 上並補描述

[APP-28969] feat: completed handleCliclAvatar helper

---

lib/hooks/__test__/translation.test.ts
lib/hooks/useTranslation.ts
playground/App.tsx
playground/Translation.tsx

[APP-29093](https://17media.atlassian.net/browse/APP-29093)
[APP-29094](https://17media.atlassian.net/browse/APP-29094)
[APP-29095](https://17media.atlassian.net/browse/APP-29095)
[APP-29096](https://17media.atlassian.net/browse/APP-29096)
完成 useTranslation 移植, playground, test, typedoc

Feat/app 25726/use translation

---

lib/17liveMessageTunnel.tsx
lib/helpers/__test__/handleClickAvatar.test.ts
lib/helpers/handleClickAvatar.ts
lib/hooks/useMockLeaderboard.ts
lib/service/leaderboardEventory.service.ts
lib/types.ts
lib/utils.ts
playground/TypeApi.tsx
playground/TypeApi2.tsx

[APP-29106](https://17media.atlassian.net/browse/APP-29106)
testcase 包含 web 開播, ios/android 開播&沒開播
web iframe 無

[APP-29106] feat: add useDeepLink testcase and typedoc

---

lib/hooks/__test__/typeApi.test.ts
lib/hooks/useTypeApi.ts
playground/TypeApi.tsx
playground/TypeApi2.tsx
tsconfig.json

[APP-29142](https://17media.atlassian.net/browse/APP-29142)
[APP-29143](https://17media.atlassian.net/browse/APP-29143)
[APP-29144](https://17media.atlassian.net/browse/APP-29144)
[APP-29145](https://17media.atlassian.net/browse/APP-29145)
刪除不需要的type，更新build檔案

Feat/app 25765/use type api other cases

---

playground/ScratchOff.tsx

[APP-30076](https://17media.atlassian.net/browse/APP-30076)
- 增加 image url, width, height input
- 增加 using default setting
- 增加 generate key without duplicate

[APP-30076] feat: enhance scratch off example

---

lib/types.ts
lib/utils.ts
playground/App.tsx
playground/Copy.tsx

https://17media.atlassian.net/browse/APP-25730
& playground

[APP-25730] copy function

---

lib/components/ScratchOffCard/index.tsx

[APP-30188](https://17media.atlassian.net/browse/APP-30188)
- 移除內容質中（已經讓內容外部可以 customize 了, css 應該也外部自己處理就好）
- 增加內容超過圖片 hidden

[APP-30188] fix: scratch off component enhance

---

lib/hooks/useKeyboard.ts

useEffect unmout 正確處理 removeListener

[modi] useEffect unmount

---

lib/components/ScratchOffCard/index.tsx
playground/ScratchOff.tsx

[APP-30342](https://17media.atlassian.net/browse/APP-30342)

Fix/app 30342/scratch off safari bug

---

dist/service/leaderboardEventory.service.js
lib/service/leaderboardEventory.service.ts

[APP-30508](https://17media.atlassian.net/browse/APP-30508)
榜單是處於無資料狀態，response不會會傳data欄位，所以在修正中需要加判斷

fix: [APP-30508] fix data empty bug

---

lib/17liveMessageTunnel.tsx
lib/hooks/useFollower.ts
lib/service/follower.service.ts
lib/service/leaderboardEventory.service.ts
lib/utils.ts
playground/Follower.tsx

https://17media.atlassian.net/browse/APP-34940

[APP-34940] jwt phase 1

---

lib/service/cacheManager.service.ts
lib/service/leaderboardEventory.service.ts

[APP-35991](https://17media.atlassian.net/browse/APP-35991)
實作 cache manager

feat: [APP-35778][APP-35991] finished cache manager

---

lib/hooks/useTypeApi.ts

https://17media.atlassian.net/browse/APP-35206

[APP-35206] add change event

---

lib/service/cacheManager.service.ts
lib/service/leaderboardEventory.service.ts

[APP-48493](https://17media.atlassian.net/browse/APP-48493)
Parse eventory api cursor for cache api
cursor  => {timestamp}:{total count}:{start}:{shard size}-{hash value}
parsedCursor => {total count}:{start}:{shard size}

feat: [APP-47589][APP-48493] parsed fetch url and remove await set cache

---

lib/service/axios.ts
lib/service/leaderboardEventory.service.ts
lib/utils.ts

feat: [APP-57461] update cn api domain

---

lib/constants/index.ts
lib/hooks/useSentry.ts
package.json
playground/App.tsx
playground/Sentry.tsx
yarn.lock

[APP-56992](https://17media.atlassian.net/browse/APP-56992)
- add useSentry hook.
- add useSentry playground.

[APP-56992] feat: add sentry lib and playground

---

lib/hooks/useTypeApi.ts
lib/service/cacheManager.service.ts

https://17media.atlassian.net/browse/APP-57112
https://17media.atlassian.net/browse/APP-57208
修改api參數和error log

feat: [APP-55719] add cache strategy prop and change error log

---

lib/hooks/useTypeApi.ts
lib/service/cacheManager.service.ts

Revert "feat: [APP-55719] add cache strategy prop and change error log"

---

lib/hooks/useTypeApi.ts
lib/service/cacheManager.service.ts
lib/service/leaderboardEventory.service.ts

[APP-58156](https://17media.atlassian.net/browse/APP-58156)
[APP-58258](https://17media.atlassian.net/browse/APP-58258)
fix network first, network only
fix client browser doesn't support cache api bug

fix: [APP-58207] fix strategy & client browser doesn't support cache api bug

---

lib/hooks/__test__/typeApi.test.ts
playground/TypeApi.tsx
playground/TypeApi2.tsx

[APP-60289](https://17media.atlassian.net/browse/APP-60289)
[APP-60269](https://17media.atlassian.net/browse/APP-60269)
更新新增功能的playground範例和unit test
[APP-60289]: https://17media.atlassian.net/browse/APP-60289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-60269]: https://17media.atlassian.net/browse/APP-60269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [APP-60150][APP-60269][APP-60289] update api playground

---

.eslintrc.js
lib/constants/index.ts
lib/service/axios.ts
lib/service/leaderboardEventory.service.ts
lib/utils.ts

[APP-61681](https://17media.atlassian.net/browse/APP-61681)
- add uat
- 統一管理 constant
[APP-61681]: https://17media.atlassian.net/browse/APP-61681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-61681] feat: add uat prepare and control data by one source constant

---

lib/enums.ts
lib/hooks/useTypeApi.ts
lib/service/axios.ts
lib/service/leaderboardEventory.service.ts
lib/utils.ts

[APP-80325](https://17media.atlassian.net/browse/APP-80325)
specified api endpoint env
[APP-80325]: https://17media.atlassian.net/browse/APP-80325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

tech: [APP-80325] specified api endpoint env

---

.codacy.yml
.github/CODEOWNERS

https://17media.atlassian.net/browse/SRE-8950
根據會議決議第 14 條申請忽略特定 File
https://docs.google.com/spreadsheets/d/1wTk41M439ZjhpKL3OstAn1RotCCbnYbqfoYfunEFgYo/edit?resourcekey=&gid=1717126955#gid=1717126955

[SRE-8950] add ignore files

---

lib/hooks/useTypeApi.ts
lib/service/leaderboardEventory.service.ts
lib/types.ts
playground/TypeApi.tsx

https://17media.atlassian.net/browse/APP-113701

[APP-113701] update useTypeApi to support over 3000 items and filter count

---

index.html
lib/components/BasePopup.tsx
lib/components/BasePopup/index.tsx
lib/helpers/cssHelper.ts
playground/App.tsx
playground/Avatar.tsx
playground/BasePopup.tsx
playground/CssHelpers.tsx

[APP-113928](https://17media.atlassian.net/browse/APP-113928)
[APP-113928]: https://17media.atlassian.net/browse/APP-113928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-113928] helper class and basepopup component

---

.eslintrc.js
index.html
lib/components/Avatar/index.tsx
lib/components/BasePopup/index.tsx
lib/helpers/cssHelper.ts
playground/App.tsx
playground/Avatar.tsx
playground/BasePopup.tsx
playground/CssHelpers.tsx

[APP-113921](https://17media.atlassian.net/browse/APP-113921)
新增 avatar component
[APP-113921]: https://17media.atlassian.net/browse/APP-113921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-113921] add avatar component

---

lib/components/LottoBall/index.tsx
playground/App.tsx
playground/LottoBall.tsx

https://17media.atlassian.net/browse/APP-114643

[APP-114643] add lotto ball component

---

lib/components/Score/index.tsx
lib/hooks/useScore.ts
playground/App.tsx
playground/LeaderboardScore.tsx

https://17media.atlassian.net/browse/APP-114644

[APP-114644] add score component
